language: android
sudo: required
jdk: oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - ANDROID_API_LEVEL=28
  - EMULATOR_API_LEVEL=22
  - ANDROID_BUILD_TOOLS=28
  - ADB_INSTALL_TIMEOUT=5
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - build-tools-27.0.3
  - android-$ANDROID_API_LEVEL
  - android-$EMULATOR_API_LEVEL
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  - addon-google_apis-google-28
  - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
  - sys-img-x86_64-android-$EMULATOR_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+


before_install:
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "platforms;android-27"
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- openssl aes-256-cbc -K $encrypted_3be5249f0b97_key -iv $encrypted_3be5249f0b97_iv -in signing/google-services.json.enc -out mobile-ui/google-services.json -d
- openssl aes-256-cbc -K $encrypted_6e575f0fc68e_key -iv $encrypted_6e575f0fc68e_iv -in signing/pkcs8_privatekey.pem.enc -out mobile-ui/src/main/assets/pem/pkcs8_privatekey.pem -d
- chmod +x keysSetup.sh
- bash keysSetup.sh
- chmod +x gradlew
- "./gradlew dependencies -q --console=plain || true"


before_script:
- android list sdk --extended --no-ui --all
- android list targets
- echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL,sys-img-x86_64-android-$EMULATOR_API_LEVEL
- echo "n" | android create avd --name test -t android-22 --abi default/armeabi-v7a
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator

# Turn off animations
- adb shell settings put global window_animation_scale 0 &
- adb shell settings put global transition_animation_scale 0 &
- adb shell settings put global animator_duration_scale 0 &

# Wake up
- sleep 20
- adb shell input keyevent 82 &


script:
- "./gradlew build jacocoTestReport assembleAndroidTest  -q --console=plain"
- "./gradlew check -q --console=plain"
- "./gradlew connectedCheck -q --console=plain"


after_success:
- bash <(curl -s https://codecov.io/bash)
