codecov:
  branch: feature/clean-architecture-implementation
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default: off
      data:
        target: 50%
        flags: data
      domain:
        target: 50%
        flags: domain
      presentation:
        target: 50%
        flags: presentation
      remote:
        target: 50%
        flags: remote
    patch: false
    changes: false

  flags:
    data:
      paths:
        - paybill-manager/data
    domain:
      paths:
        - paybill-manager/domain
    presentation:
      paths:
        - paybill-manager/presentation
    remote:
      paths:
        - paybill-manager/remote


  ignore:
  - "**/*Activity.kt"
  - "**/*Fragment.kt"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags"
  behavior: default
  require_changes: no
